spring.application.name=hotel
server.port=8060

spring.datasource.url=jdbc:mysql://localhost:3406/hotel_db
spring.datasource.username=root
spring.datasource.password=root

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Data SQL
spring.sql.init.mode=always

# Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alexandre.brouzes@iut-rodez.fr
spring.mail.password=nwntcfvipygcaqzq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true