apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: false
    editable: true

  - name: MySQL-Hotel
    uid: mysql-hotel
    type: mysql
    access: proxy
    url: mysql:3306
    user: root
    jsonData:
      database: hotel_db_refactor
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    secureJsonData:
      password: root
    editable: true
